apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wishlist
  labels:
    app: wishlist
spec:
  to:
    kind: Service
    name: wishlist
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None