apiVersion: v1
kind: Service
metadata:
  name: wishlist
  labels:
    app: wishlist
spec:
  type: ClusterIP
  selector:
    app: wishlist
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
